---
title: "HW 2"
author: "Group 2"
date: "3/10/2021"
output: 
  pdf_document:
    toc: TRUE
    toc_levels: TRUE
    

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(caret)

```

##Setup


```{r load-data}
data_raw <- read.csv("https://raw.githubusercontent.com/Jagdish16/CUNY_DATA_621/main/homework_2/classification-output-data.csv")
```

```{r, rawConfusionMatrixTable}
# For the confusion matrix, we are only interested in the class and scored.class variables,
# so we select only these variables and ignre the rest.
confusion_matrix_table <- data_raw %>% 
  select(class, scored.class)

# For readability purposes, rename 'scored.class' to Predicted, and 'class' to Actual.
dplyr::rename(confusion_matrix_table, Predicted = scored.class, Actual = class) %>%
    # Convert numeric boolean values to human readable values.
    mutate(Predicted = recode(Predicted,
                               '0' = 'Negative', 
                               '1' = 'Positive'),
         Actual = recode(Actual,
                        '0' = 'Negative', 
                        '1' = 'Positive')) %>%
  table()
```


## Functions

```{}
```

### Accuracy
```{r}

accuracy <- function(){

}

accuracy()

```
### Classification Error Rate
```{r}

class_error_rate <- function(){
  
}

```
### Precision
```{r}

precision <- function(){
  
}

```
### Sensitivty
```{r}
#note: there is a built in function in package caret called sensitivity
sensitivity <- function(){
  
} 
```
### Specificity
```{r}

specificity <- function(){
  
}
```
### FI Score
```{r}
#should be based on the previous functions, so something like the below...
fi_score <- function(x){
  2*sensitivity(x)*precision(x)/(precision(x) + sensitivity(x))
}
```
###

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
