---
title: "project_1"
author: "Richard"
date: "2/22/2021"
output: html_document
---
# Importing packages

```{r}

```
#loading dataset
```{r}
url = "https://raw.githubusercontent.com/Jagdish16/CUNY_DATA_621/main/project_1/moneyball-training-data.csv"
training = read.csv(url)

training
```
# 
```{r}

get_mean = function(df,column){
  string = summary(df[column])[4]
  mean = as.numeric(unlist(strsplit(string,"[:]"))[2])
  return (mean)
}

columns = names(training)
has_na = columns[apply(training,2,anyNA)]
for (var in has_na){
  x = training[var]
  x[is.na(x)] = get_mean(training,var)
  training[var] = x
}


num_col = dim(training)[2]
wins = columns[2]
variables = columns[3:num_col]

corr = c()
for (variable in variables){
  corr= c(corr,cor(training[wins],training[variable]))
}

correlation = data.frame(matrix(c(variables,corr),ncol = 2))
names(correlation) = c("variable","correlation")
correlation
```
# Scatter plot
```{r}
pairs(training[2:num_col], upper.pannel = NULL)

```

```{r}

```

